title: andreyka26 live
google_analytics: G-71R0HBMGS3
description: >- # this means to ignore newlines until "baseurl:"
  I am Software Engineer at Microsoft. This is my live blog where I would like to share my thoughts that are not related to software engineering.

url: "https://live.andreyka26.com" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

widedefault: "/assets/wide-default.png"
squaredefault: "/assets/square-default.png"

# Navigation
urls:
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Categories
      url: /categories
    - text: Privacy Policy
      url: /privacy-policy
    - text: Terms of Use
      url: /terms-of-use

# Edit Author details (For multi authors check _data/authors.yml)
author_logo: profile.png
author: Andrii Bui
author_bio: Hi, my name is Andrii. I'm Software Engineer at Microsoft with 5 years of experience. 
author_location: Ukraine
#typewrite-text: Healthcare, psychology, neurobiology, and different stuff.
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Software Engineer
              description: I am acting as Software Engineer working on Backend services for M365
              visibility: true
            - company_name: Epam Systems
              company_logo: epam.png
              company_url: https://www.epam.com
              designation: Senior Software Engineer
              description: Developing project with Oil domain(the project is under NDA). The system is a search service that searches through a lot of external and internal systems and services(REST API, SOAP, SQL Server, Cognitive Search). Playing the key software engineer role on the backend side, designing and implementing software architecture, improve performance, provide security compliance. Also developing and maintaining Java Solution which works with active directory and Kafka acting as an ETL job.
              visibility: true
            - company_name: Eleks
              company_logo: eleks.png
              company_url: https://www.eleks.com
              designation: Middle Software Engineer
              description: Developing new features, designing application architecture, and maintaining current behavior on 2C2P (https://www.2c2p.com/). The system is a payment gateway between different payment providers. Playing the role as a key developer on the project delegated to me along with the QA team.
              visibility: true
            - company_name: Magnise
              company_logo: magnise.jfif
              company_url: https://magnise.com
              designation: Junior Software Engineer
              description: Developing the news monitoring system Alphateka (https://alphateka.com). The system monitors social networks, online news, TV, and Radio. It provides quick articles/posts querying with sentiment and clustering analysis. It is able to build analytical charts on the data and notify about different alerts. Playing the role as a backend developer along with 2 frontend developers, 3 backend developers, PM, QA.
              visibility: true

# social links
github_username:  andreyka26-git
facebook_username: profile.php?id=100017215509428
linkedin_username: andrii-bui-a55b39166
instagram_username: andreyka26_se
telegram_username: programming_space
youtube_username: "@andreyka26_se"

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: /:title

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: false
show_author_project_details: false

# pagination of posts
paginate: 6
per_page: 6
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: false
  authors:
    output: false

defaults:
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/masonry-layout/README.md
  - readme.md


destination: ./build
